version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install -g npm@latest
  
  pre_build:
    commands:
      - echo Pre-build phase started...
      - echo Building frontend...
      - cd todo-frontend
      - npm ci
      - echo Building backend...
      - cd ../todo-backend
      - ./mvnw clean
  
  build:
    commands:
      - echo Build phase started...
      - echo Building frontend...
      - cd ../todo-frontend
      - npm run build
      - echo Building backend...
      - cd ../todo-backend
      - ./mvnw package -DskipTests
  
  post_build:
    commands:
      - echo Post-build phase started...
      - echo Preparing deployment packages...
      - mkdir -p artifacts
      - cp todo-backend/target/*.jar artifacts/
      - cp -r todo-frontend/build/* artifacts/static/
      - echo Build completed on `date`

artifacts:
  files:
    - artifacts/**/*
    - appspec.yml
    - scripts/**/*
  discard-paths: no