name: Deploy Backend to AWS
# s
on:
  push:
    branches:
      - main
    paths:
      - 'todo-backend/**'
      - '.github/workflows/aws-backend-deploy.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'
        cache: 'maven'
        
    - name: Build with Maven
      run: |
        cd todo-backend
        ./mvnw clean package -DskipTests
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}
        
    - name: Create deployment package
      run: |
        mkdir -p deployment/scripts
        cp todo-backend/target/*.jar deployment/app.jar
        cp -r scripts/* deployment/scripts/
        cp appspec.yml deployment/
        cd deployment
        zip -r ../backend-deployment.zip *
        
    - name: Deploy to AWS CodeDeploy
      id: deploy
      run: |
        aws deploy create-deployment \
          --application-name todo-app \
          --deployment-group-name todo-backend-group \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --s3-location bucket=${{ secrets.AWS_S3_BUCKET }},bundleType=zip,key=backend-deployment.zip \
          --file-exists-behavior OVERWRITE
        
    - name: Upload artifact to S3
      run: |
        aws s3 cp backend-deployment.zip s3://${{ secrets.AWS_S3_BUCKET }}/backend-deployment.zip
        
    - name: Deployment status
      run: |
        echo "Deployment triggered successfully"
        echo "Check AWS CodeDeploy console for deployment status"