name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: tododb
          POSTGRES_USER: basselfa
          POSTGRES_PASSWORD: 1234
        ports:
          - 5432:5432
        # Add health check to ensure postgres is ready before tests run
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    # Add your build and test steps here
    # For example:
    # - name: Build and test
    #   run: mvn -B package --file pom.xml