name: Deploy Frontend to Netlify with SonarCloud Analysis

on:
  push:
    branches:
      - main  
  workflow_dispatch:  
# s
jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './todo-frontend/package-lock.json'
      
      - name: Install dependencies
        run: |
          cd todo-frontend
          npm ci
      
      - name: Run tests with coverage
        run: |
          cd todo-frontend
          npm test -- --coverage --watchAll=false
        continue-on-error: true  # Continue even if tests fail
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: sonarcloud  # This job will run after sonarcloud job completes
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # You can adjust this to your preferred Node.js version
          cache: 'npm'
          cache-dependency-path: './todo-frontend/package-lock.json'
      
      - name: Install dependencies
        run: |
          cd todo-frontend
          npm ci
      
      - name: Build project
        run: |
          cd todo-frontend
          npm run build
      
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: './todo-frontend/build'
          production-branch: main  # Change this to your main branch name if different
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 5

      - name: Verify deployment
        run: |
          echo "Deployment complete! Your site should be live now."
          echo "If you're experiencing issues, please check:"
          echo "1. Netlify site settings at https://app.netlify.com/sites/${{ secrets.NETLIFY_SITE_ID }}/settings/general"
          echo "2. Build logs at https://app.netlify.com/sites/${{ secrets.NETLIFY_SITE_ID }}/deploys"