name: Deploy to Render

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Backend to Render
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Verify Render credentials
        run: |
          if [ -z "${{ secrets.RENDER_API_KEY }}" ]; then
            echo "::error::RENDER_API_KEY is not set. Please add it to your repository secrets."
            exit 1
          fi
          if [ -z "${{ secrets.RENDER_SERVICE_ID }}" ]; then
            echo "::error::RENDER_SERVICE_ID is not set. Please add it to your repository secrets."
            exit 1
          fi
          echo "Render credentials verified successfully."
        
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          
      - name: Verify Deployment
        run: |
          echo "Deployment triggered successfully!"
          echo "Deployment process completed. Check Render dashboard for deployment status."e
